server:
  port: 8080
  servlet:
    context-path: /officialAccounts
spring:
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  redis:
        database: 0
        host: www.hiyzx.cn
        port: 6379
        password: yzx362311
        lettuce:
          pool:
            max-active: 8
            max-idle: 8
            min-idle: 0

wx:
  token: hiyzx
  appID: wxebe3398569e96ff9
  appSecret: fe86f9b1b4da92ddba8f5d511091806d
http:
  wx:
    scheme: https
    hostname: api.weixin.qq.com
    port: 443

project:
  version: @project.version@

# 描述信息
info:
  author: zero
  version: @project.version@
  buildTime: @project.build.time@
