server:
  port: 8080
  servlet:
    context-path: /appointment
spring:
  datasource:
    url: jdbc:mysql://www.hiyzx.cn:3306/appointment?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: yzx362311
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
          connection-test-query: select 1 from dual
          connection-timeout: 30000
          idle-timeout: 60000
          max-lifetime: 1800000
          maximum-pool-size: 50
          minimum-idle: 50
mybatis:
    type-aliases-package: org.zero.spring.mybatis.po
    mapper-locations: classpath:org.zero.miniprogram.appointment.dao/*.xml
    configuration:
      cache-enabled: true
mapper:
    mappers:
        - org.zero.miniprogram.appointment.config.MyMapper
    not-empty: false
    identity: MYSQL
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
logging:
  level:
    org.springframework.web: info
    springframework.transaction: info
    org.mybatis: info
    org.zero: info